import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default ts.config(
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs['flat/recommended'],
  prettier,
  ...svelte.configs['flat/prettier'],
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      // typescript-eslint v8+ needs `tsconfigRootDir` to be explicit
      // when more than one workspace under the same git tree has a
      // `tsconfig.json` (we have web/app + web/packages/logic-mesh).
      // Pinning to this config file's own directory makes the IDE pick
      // the correct workspace per file.
      parserOptions: {
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      // Intentionally-unused parameters/vars use a `_` prefix.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Hard errors. New code must keep this surface clean. Existing
      // intentional `any`/`Map` cases are tagged with inline
      // `eslint-disable-next-line` comments at the call site (see
      // `pasteSelection` in +page.svelte) so they're visible.
      '@typescript-eslint/no-explicit-any': 'error',
      'svelte/require-each-key': 'error',
      'svelte/prefer-svelte-reactivity': 'error',
    },
  },
  {
    // Generated by SvelteKit / vite build outputs / wasm-pack — never
    // our source.
    ignores: [
      'build/',
      '.svelte-kit/',
      'dist/',
      'node_modules/',
      'src/lib/components/ui/**',
    ],
  },
);
