import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default ts.config(
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs['flat/recommended'],
  prettier,
  ...svelte.configs['flat/prettier'],
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      // typescript-eslint v8+ needs `tsconfigRootDir` to be explicit
      // when more than one workspace under the same git tree has a
      // `tsconfig.json` (we have web/app + web/packages/logic-mesh).
      // Pinning to this config file's own directory makes the IDE pick
      // the correct workspace per file.
      parserOptions: {
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      // Intentionally-unused parameters/vars use a `_` prefix.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // The program-loading path consumes untyped JSON; tightening
      // these to error would require landing the type-narrowing work
      // alongside this lint setup. Surface as warnings for now so
      // they're visible in CI without blocking the initial green.
      '@typescript-eslint/no-explicit-any': 'warn',
      // New in `eslint-plugin-svelte` v3:
      //   - `require-each-key` is a perf hint, not a correctness one;
      //     most of our `{#each}` lists are short and replace-in-place.
      //   - `prefer-svelte-reactivity` would flip our internal lookup
      //     `Map`s (e.g. `blockInstances`) to `SvelteMap`s. They aren't
      //     used as reactive sources today (consumers `get` on demand
      //     rather than `$derived`-ing the whole map), so the warning
      //     is defensive rather than load-bearing.
      // Both are real cleanups, just not for this PR.
      'svelte/require-each-key': 'warn',
      'svelte/prefer-svelte-reactivity': 'warn',
    },
  },
  {
    // Generated by SvelteKit / vite build outputs / wasm-pack — never
    // our source.
    ignores: [
      'build/',
      '.svelte-kit/',
      'dist/',
      'node_modules/',
      'src/lib/components/ui/**',
    ],
  },
);
