[build]
# rustflags = ["--cfg", 'feature="value"', 
# 			"--cfg", 'feature="units"',
# 			"--cfg", 'feature="units-db"',
# 			"--cfg", 'feature="timezone"',
# 			"--cfg", 'feature="timezone-db"',
# 			"--cfg", 'feature="encoders"', 
# 			"--cfg", 'feature="zinc"', 
# 			"--cfg", 'feature="zinc-encoding"',
# 			"--cfg", 'feature="zinc-decoding"',
# 			"--cfg", 'feature="json"', 
# 			"--cfg", 'feature="json-encoding"',
# 			"--cfg", 'feature="json-decoding"']