name: Publish

on:
  release:
    types: [published]

jobs:
  publishMacro:
    name: Publish block macro lib
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATES_TOKEN}
        working-directory: ./block_macro
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

  publish:
    name: Publish main crate
    runs-on: ubuntu-latest
    if: always()
    needs: publishMacro
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}